version: "3.7"

services:
  product-service:
    build: .
    container_name: product-service
    ports:
      - "8000:8000"
    depends_on:
      - product-database
    networks:
      - product-networks
    volumes:
      - .:/app/

  product-database:
    image: postgres
    container_name: product-database
    ports:
      - "5440:5432"
    environment:
      - POSTGRES_USER=product
      - POSTGRES_PASSWORD=product
      - POSTGRES_DB=product-service
    volumes:
      - ./configs/migrations/:/docker-entrypoint-initdb.d/
      - product_database_vol:/var/lib/postgresql/data
    networks:
      - product-networks

volumes:
  product_database_vol: {}

networks:
  product-networks:
    driver: bridge